### ISSUE TITLE
NPE with DeluxeChat

### ISSUE THREAD

**Issue by DrkMatr1984** [DrkMatr1984/dsTitles#2]
`[08:35:25] [Server thread/INFO]: [Mail] Loaded Mail for 4eb4a4f9-2fc4-42b4-b3a8-bb29af9bc364 from MySQL, took 6 ms
[08:35:26] [Server thread/INFO]: Myekaan[/98.235.127.235:56491] logged in with entity id 128 at ([Lobby]1041.898994118631, 4.0, -373.8335428208597)
[08:35:28] [Server thread/WARN]: [CraftBook] §cWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[08:35:29] [Craft Scheduler Thread - 15/INFO]: [VanishNoPacket] Error: Could not check if plugin was up to date. Will try later
[08:35:29] [Craft Scheduler Thread - 15/INFO]: [VanishNoPacket] Exception message: Server returned HTTP response code: 403 for URL: https://api.curseforge.com/servermods/files?projectIds=30949
[08:35:34] [Async Chat Thread - #0/WARN]: 43437 [Async Chat Thread - #0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - is starting.

[08:35:34] [Async Chat Thread - #0/WARN]: 43755 [Async Chat Thread - #0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-2 - is starting.

[08:35:34] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:35:43] [Async Chat Thread - #0/WARN]: 52874 [Async Chat Thread - #0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-3 - is starting.

[08:35:43] [Async Chat Thread - #0/WARN]: 53261 [Async Chat Thread - #0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-4 - is starting.

[08:35:44] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:36:22] [Server thread/INFO]: Myekaan issued server command: /deluxechat reload
[08:36:22] [Server thread/INFO]: [DeluxeChat] 1 formats loaded!
[08:36:24] [Async Chat Thread - #0/WARN]: 93983 [Async Chat Thread - #0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-5 - is starting.

[08:36:24] [Async Chat Thread - #0/WARN]: 94112 [Async Chat Thread - #0] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-6 - is starting.

[08:36:24] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:37:18] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:37:18] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:37:18] [Server thread/INFO]: Admins: Myekaan
[08:37:54] [Async Chat Thread - #1/WARN]: 183957 [Async Chat Thread - #1] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-7 - is starting.

[08:37:54] [Async Chat Thread - #1/WARN]: 184077 [Async Chat Thread - #1] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-8 - is starting.

[08:37:54] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:39:14] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:39:14] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:39:14] [Server thread/INFO]: Admins: Myekaan
[08:40:27] [Server thread/WARN]: [CraftBook] §cWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[08:41:10] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:41:10] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:41:10] [Server thread/INFO]: Admins: Myekaan
[08:41:12] [Server thread/INFO]: Myekaan issued server command: /dstitle reload
[08:41:16] [Server thread/INFO]: Myekaan issued server command: /dstitles reload
[08:41:23] [Server thread/INFO]: Myekaan issued server command: /dstitles:title reload
[08:41:29] [Server thread/INFO]: Myekaan issued server command: /dstitle:title reload
[08:41:32] [Async Chat Thread - #2/WARN]: 402074 [Async Chat Thread - #2] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-9 - is starting.

[08:41:32] [Async Chat Thread - #2/WARN]: 402216 [Async Chat Thread - #2] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-10 - is starting.

[08:41:33] [Async Chat Thread - #2/ERROR]: Could not pass event AsyncPlayerChatEvent to DeluxeChat v1.10.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1273) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1211) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.a(AbstractListenerPlayIn.java:85) [denizen-0.9.8-SNAPSHOT.jar:?]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at com.kaltiz.dsTitle.TitleManager.getPrefixChatTag(TitleManager.java:156) ~[?:?]
    at denniss17.dsTitle.Placeholders.DeluxeChatHook$1.onPlaceholderRequest(DeluxeChatHook.java:27) ~[?:?]
    at me.clip.deluxechat.placeholders.PlaceholderHandler.setPlaceholders(PlaceholderHandler.java:485) ~[?:?]
    at me.clip.deluxechat.DeluxeChat.getFancyChatFormat(DeluxeChat.java:950) ~[?:?]
    at me.clip.deluxechat.listeners.AsyncPlayerChatListener.onChat(AsyncPlayerChatListener.java:83) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    ... 12 more
[08:41:33] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:41:38] [Async Chat Thread - #2/WARN]: 407774 [Async Chat Thread - #2] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-11 - is starting.

[08:41:38] [Async Chat Thread - #2/WARN]: 407950 [Async Chat Thread - #2] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-12 - is starting.

[08:41:38] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> wtf
[08:42:02] [Server thread/INFO]: Myekaan issued server command: /dstitle:title prefix
[08:42:13] [Server thread/INFO]: Myekaan issued server command: /dstitle:title prefix set Owner
[08:42:15] [Async Chat Thread - #2/WARN]: 445325 [Async Chat Thread - #2] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-13 - is starting.

[08:42:16] [Async Chat Thread - #2/WARN]: 445432 [Async Chat Thread - #2] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-14 - is starting.

[08:42:16] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:43:06] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:43:06] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:43:06] [Server thread/INFO]: Admins: Myekaan
[08:44:12] [Server thread/INFO]: Myekaan issued server command: /dstitle:title reload
[08:44:22] [Server thread/INFO]: Myekaan issued server command: /deluxechat reload
[08:44:22] [Server thread/INFO]: [DeluxeChat] 1 formats loaded!
[08:44:24] [Async Chat Thread - #3/WARN]: 573783 [Async Chat Thread - #3] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-15 - is starting.

[08:44:24] [Async Chat Thread - #3/WARN]: 574056 [Async Chat Thread - #3] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-16 - is starting.

[08:44:24] [Async Chat Thread - #3/ERROR]: Could not pass event AsyncPlayerChatEvent to DeluxeChat v1.10.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1273) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1211) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at net.aufdemrand.denizen.utilities.packets.intercept.AbstractListenerPlayIn.a(AbstractListenerPlayIn.java:85) [denizen-0.9.8-SNAPSHOT.jar:?]
    at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at com.kaltiz.dsTitle.TitleManager.getPrefixChatTag(TitleManager.java:156) ~[?:?]
    at denniss17.dsTitle.Placeholders.DeluxeChatHook$1.onPlaceholderRequest(DeluxeChatHook.java:27) ~[?:?]
    at me.clip.deluxechat.placeholders.PlaceholderHandler.setPlaceholders(PlaceholderHandler.java:485) ~[?:?]
    at me.clip.deluxechat.DeluxeChat.getFancyChatFormat(DeluxeChat.java:950) ~[?:?]
    at me.clip.deluxechat.listeners.AsyncPlayerChatListener.onChat(AsyncPlayerChatListener.java:83) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-078e2f8-7f9fbe5]
    ... 12 more
[08:44:24] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:44:27] [Async Chat Thread - #3/WARN]: 577133 [Async Chat Thread - #3] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-17 - is starting.

[08:44:27] [Async Chat Thread - #3/WARN]: 577279 [Async Chat Thread - #3] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-18 - is starting.

[08:44:28] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:45:02] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:45:02] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:45:02] [Server thread/INFO]: Admins: Myekaan
[08:45:27] [Server thread/WARN]: [CraftBook] §cWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[08:46:58] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:46:58] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:46:58] [Server thread/INFO]: Admins: Myekaan
[08:47:41] [Server thread/INFO]: Myekaan issued server command: /deluxechat reload
[08:47:41] [Server thread/INFO]: [DeluxeChat] 1 formats loaded!
[08:47:43] [Async Chat Thread - #4/WARN]: 773192 [Async Chat Thread - #4] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-19 - is starting.

[08:47:44] [Async Chat Thread - #4/WARN]: 773404 [Async Chat Thread - #4] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-20 - is starting.

[08:47:44] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> hey
[08:48:39] [Server thread/INFO]: Myekaan issued server command: /deluxechat reload
[08:48:39] [Server thread/INFO]: [DeluxeChat] 1 formats loaded!
[08:48:47] [Server thread/INFO]: Myekaan issued server command: /deluxechat reload
[08:48:47] [Server thread/INFO]: [DeluxeChat] 1 formats loaded!
[08:48:50] [Async Chat Thread - #5/WARN]: 840100 [Async Chat Thread - #5] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-21 - is starting.

[08:48:50] [Async Chat Thread - #5/WARN]: 840221 [Async Chat Thread - #5] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-22 - is starting.

[08:48:51] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> sd
[08:48:54] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:48:54] [Server thread/INFO]: There are 1 out of maximum 1,000 players online.
[08:48:54] [Server thread/INFO]: Admins: Myekaan
[08:48:56] [Server thread/INFO]: Myekaan issued server command: /dstitle:title prefix
[08:49:10] [Server thread/INFO]: Myekaan issued server command: /dstitle:title prefix set God
[08:49:15] [Server thread/INFO]: Myekaan issued server command: /dstitle:title prefix set GOD
[08:49:19] [Async Chat Thread - #5/WARN]: 868403 [Async Chat Thread - #5] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-23 - is starting.

[08:49:19] [Async Chat Thread - #5/WARN]: 868551 [Async Chat Thread - #5] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-24 - is starting.

[08:49:19] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> test
[08:49:34] [Async Chat Thread - #5/WARN]: 883403 [Async Chat Thread - #5] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-25 - is starting.

[08:49:34] [Async Chat Thread - #5/WARN]: 883511 [Async Chat Thread - #5] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-26 - is starting.

[08:49:34] [Server thread/INFO]: [Lobby]<Myekaan Shreiner> I am Da Bomb Diggity
[08:50:07] [Server thread/INFO]: Myekaan lost connection: Disconnected
[08:50:07] [Server thread/INFO]: [Mail] Saving Mail for 4eb4a4f9-2fc4-42b4-b3a8-bb29af9bc364 to MySQL
[08:50:07] [Server thread/INFO]: [Mail] Saved Mail for 4eb4a4f9-2fc4-42b4-b3a8-bb29af9bc364 to MySQL, took 66 ms
[08:50:27] [Server thread/WARN]: [CraftBook] §cWarning! You have no mechanics enabled, the plugin will appear to do nothing until a feature is enabled!
[08:50:50] [Server thread/INFO]: CONSOLE issued server command: /list 
[08:50:50] [Server thread/INFO]: There are 0 out of maximum 1,000 players online.
`

**Comment by DrkMatr1984** [comment]
I fixed this recently. It happened when a player had not set their title yet. A default prefix and suffix had to be set or null point errors ensued.

Maybe in the future I will make it check if a default prefix/suffix is set, and if not, to not send anything. This will prevent null points but allow server owners to have blank chattags.
